config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: {  omniauth_callbacks: "omniauth_callbacks" }
  root 'hello#index'
  resources :hello, only: [:index]
  resources :users, only: [:show]
  resources :tweets, only: %i[index create show edit destroy update] do
    resources :likes, only: %i[create destroy]
    resources :comments, only: [:create]
  end
  post '/callback' => 'linebot#callback'
end

app/models/tweet.rb
# frozen_string_literal: true

class Tweet < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :comments, dependent: :destroy
  validates :title, presence: true
  validates :tantou, presence: true
  enum completed: { outstanding: 0, in_progress: 1, closed: 2 }
end

app/controllers/tweets_controller.rb
# frozen_string_literal: true

class TweetsController < ApplicationController
  before_action :authenticate_user!
  def index
    @tweets = Tweet.order('date')
    @tweet = Tweet.new
    @q = Tweet.ransack(params[:q])
    @boards = @q.result.page(params[:page]).per(10)
  end

  def create
    @tweet = current_user.tweets.create!(tweet_params)
    @tweet.user_uid = current_user.uid
    @tweet.save
    @tweets = Tweet.order('date')
    @q = Tweet.ransack(params[:q])
    @boards = @q.result.page(params[:page]).per(10)
  end

  def show
    @tweet = Tweet.find(params[:id])
    @comments = @tweet.comments
    @comment = Comment.new
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    @tweet = Tweet.find(params[:id])
    if @tweet.update(tweet_params)
      redirect_to tweets_path(@tweet), notice: '対応ステータスを更新しました'
    else
      render :show
    end
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy 
    redirect_to tweets_path
  end

  private

  def tweet_params
    params.require(:tweet).permit(:title, :tantou, :body, :time, :completed)
  end
end

app/helpers/tweets_helper.rb
# frozen_string_literal: true

module TweetsHelper
end

app/views/tweets/_tweets.html.erb
<div class="col-14 tweets">
  <table class="table bg-white ">
    <thead>
      <tr>
        <th class="col-1">ステータス</th>
        <th class="col-2">担当</th>
        <th class="col-3">内容</th>
        <th class="col-2">締切期限</th>
        <th class="col-1">詳細</th>
        <th class="col-1">編集</th>
        <th class="col-1">削除</th>
        <th class="col-1">お気に入り</th>
      </tr>
    </thead>
  <% @boards.each do |tweet|%>
    <tbody>
      <tr>
        <div class="row">
        <td class="col-1"><%= tweet.completed_i18n%></td> 
        <td class="col-2"><%= tweet.tantou %></td>
        <td class="col-3"><%= tweet.title %></td>
        <td class="col-2"><%= tweet.time %></td>
        <td class="col-1">
          <%= link_to tweet_path(tweet) do %><i class="fas fa-comment"></i><% end %>
        </td>
        <td>
        <% if current_user == tweet.user %>
        <%= link_to edit_tweet_path(tweet),class: "col-1" do %>
        <i class="fas fa-edit"></i>
        <% end %>
        </td>
        <td>
        <%= link_to tweet_path(tweet.id),class: "col-1", method: :delete do %>
        <i class="fas fa-trash"></i>
        <% end %>
        <% end %>
        </td>
        <td>
        <% if user_signed_in? %>
        <% if current_user.already_liked?(tweet) %>
        <%= link_to tweet_like_path(id: tweet.id, tweet_id: tweet.id),class: "col-1", method: :delete do %>
        <i class="fas fa-heart"></i><%= tweet.likes.count %>
        <% end %>
        <% else %>
        <%= link_to tweet_likes_path(id: tweet.id, tweet_id: tweet.id),class: "col-1", method: :post do %>
        <i class="far fa-heart"></i><%= tweet.likes.count %>
        <% end %>
        <% end %>
        <% else %>
        <i class="far fa-heart"></i><%= tweet.likes.count %>
        <% end %>
        </td>
        </div>
      </tr>
    </tbody>
  <% end %>
  <%= paginate @boards %>
  </table>
</div>

app/views/tweets/create.js.erb
$("textarea").val("");
$("input").val("");
$('#exampleModal').modal('hide')
$('.tweets').html("<%= escape_javascript(render 'tweets', tweets: @boads) %>")

app/views/tweets/edit.html.erb
<header class="bg-dark">
  <nav class="navbar navbar-expand-lg navbar-light">
    <div class="container-fluid">
      <button class="navbar-toggler bg-white" type="button" data-bs-toggle="collapse"
        data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false"
        aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <div class="logo">
            <a class="nav-link text-white" aria-current="page" href="/">WorkShare</a>
          </div>
          <%= link_to "マイページへ", user_path(current_user),{class: "nav-link text-white"} %>
        </div>
      </div>
    </div>
  </nav>
</header>
<main>
  <div class="menu2 d-flex align-items-center box">
    <div class="container box-inner col-4">
      <div class="bg-light p-3  rounded ">
        <h1>編集</h1>
        <%= form_with model:@tweet do |f|%>
        <div class="form-group">
          <%= f.label :title,"TODO" %>
          <%= f.text_field :title, class: "form-control"%>
        </div>
        <div class="form-group">
          <%= f.label :tantou,"担当者" %>
          <%= f.text_field :tantou, class: "form-control"%>
        </div>
        <div class="form-group">
          <%= f.label :body,"内容" %>
          <%= f.text_area :body, class: "form-control"%>
        </div>
        <div class="form-group">
          <%= f.label :time,"期日" %>
          <%= f.date_field :time %>
        </div>
      </div>
      <div class="modal-footer">
        <%= link_to "戻る", tweets_path(current_user),{class: "btn btn-secondary"} %>
        <%= f.submit "変更", class: "btn btn-primary"%>
      </div>
      <% end %>
    </div>
  </div>
  </div>
</main>
<footer class="bg-dark">
  <div class="text-white text-center">
    Copyright Takumi Fujiwara ,2021 All Rights Reserved.
  </div>
</footer>

app/views/tweets/index.html.erb
<header class="bg-dark">
  <nav class="navbar navbar-expand-lg navbar-light">
    <div class="container-fluid">
      <button class="navbar-toggler bg-white" type="button" data-bs-toggle="collapse"
        data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false"
        aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <div class="logo">
            <a class="nav-link text-white" aria-current="page" href="/">WorkShare</a>
          </div>
          <%= link_to "マイページへ", user_path(current_user),{class: "nav-link text-white"} %>
        </div>
      </div>
    </div>
  </nav>
</header>
<div class="main kotei">
  <div class="container">
    <div class="row">
      <div class="col-3 mt-5">
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
          新規投稿
        </button>
        <button type="button" class="btn btn-secondary" data-bs-toggle="modal" data-bs-target="#exampleModal2">
          検索一覧
        </button>
      </div>
      <div class="table mt-2">
        <tr>
          <th>並び順</th>
          <th><%= sort_link(@q, :completed, "ステータス") %></th>
          <th><%= sort_link(@q, :time, "締め切り日") %></th>
        </tr>
      </div>
      <%= render 'tweets', tweets: @boards%>
    </div>
  </div>
</div>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">新規投稿</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= form_with model:@tweet,local:false do |f|%>
        <div class="form-group">
          <%= f.label :title,"TODO" %>
          <%= f.text_field :title, class: "form-control"%>
        </div>
        <div class="form-group">
          <%= f.label :tantou,"担当者" %>
          <%= f.text_field :tantou, class: "form-control"%>
        </div>
        <div class="form-group">
          <%= f.label :body,"内容" %>
          <%= f.text_area :body, class: "form-control"%>
        </div>
        <div class="form-group">
          <%= f.label :time,"期日" %>
          <%= f.date_field :time %>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">閉じる</button>
        <%= f.submit "投稿する", class: "btn btn-primary"%>
      </div>
      <% end %>
    </div>
  </div>
</div>

<div class="modal fade" id="exampleModal2" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">検索一覧</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <%= search_form_for @q, url: tweets_path do |f| %>
      <div class="modal-body">
        <div class="form-group">
          <%= f.label :tantou_cont, '担当者名' %>
          <%= f.search_field :tantou_cont,class: "form-control" %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">閉じる</button>
          <%= f.submit "検索", class: "btn btn-primary"%>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<footer class="bg-dark">
  <div class="text-white text-center">
    Copyright Takumi Fujiwara ,2021 All Rights Reserved.
  </div>
</footer>

app/views/tweets/show.html.erb
<header class="bg-dark">
  <nav class="navbar navbar-expand-lg navbar-light">
    <div class="container-fluid">
      <button class="navbar-toggler bg-white" type="button" data-bs-toggle="collapse"
        data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false"
        aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <div class="logo">
            <a class="nav-link text-white" aria-current="page" href="/">WorkShare</a>
          </div>
        </div>
      </div>
    </div>
  </nav>
</header>
<div class="main">
  <div class="container">
    <div class="tweet">
      <h1>TODO詳細</h1>
      <div class="bg-white">

        <div class="form">
          <p>担当者</p>
          <p><%= @tweet.tantou %></p>
        </div>

        <div class="form">
          <p>タイトル</p>
          <p><%= @tweet.title %></p>
        </div>

        <div class="form">
          <p>期限</p>
          <p><%= @tweet.time %></p>
        </div>

        <div class="form">
          <p>詳細</p>
          <p><%= @tweet.body %></p>
        </div>
        <div class="from">
          <%= form_with(model: @tweet, url: tweet_path, local: true,method: :patch, class: "form-row col-1") do |f| %>
          <%= f.select :completed, Tweet.completeds_i18n.invert, {prompt: false}, class:"form-control form-control-sm col-2" %>
          <%= f.submit "更新" %>
          <% end %>
        </div>
      </div>
      <div class="comment-wrapper">
        <p>コメント一覧</p>
        <% @comments.each do |c| %>
        <div>
          <%= image_tag c.user.image_url ,class: "user_image ",size: "60x60" if c.user.image? %>
          <%= c.user.name unless c.user.blank? %>
          <%= c.created_at.to_s(:datetime_jp) %>
          <br>
          <%= c.content %>
        </div>
        <br>
        <% end %>
        <% if user_signed_in? %>
        <%= form_with(model: [@tweet, @comment], local: true) do |f| %>
        <%= f.text_area :content,class: "col-8" %>
        <%= button_tag type: "submit" do %>
        <i class="far fa-comments"></i> コメントする
        <% end %>
        <% end %>
        <% end %>
        <%= link_to "Tweet一覧に戻る", tweets_path %>
      </div>
    </div>
  </div>
</div>
<footer class="bg-dark">
  <div class="text-white text-center">
    Copyright Takumi Fujiwara ,2021 All Rights Reserved.
  </div>
</footer>